# Generated by Django 3.1 on 2020-10-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_list',
            field=models.TextField(null=True),
        ),
    ]
