# Generated by Django 3.1 on 2020-10-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si_owner_name', models.CharField(max_length=30)),
                ('si_title', models.CharField(max_length=50)),
                ('si_form_cnt', models.CharField(max_length=50)),
                ('si_form_info', models.TextField()),
                ('si_account', models.CharField(max_length=255)),
                ('si_bankcode', models.CharField(max_length=10)),
                ('si_regdate', models.CharField(max_length=16)),
            ],
        ),
    ]
