# Generated by Django 3.1 on 2020-10-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NouserSettleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsi_owner_key', models.CharField(max_length=100)),
                ('nsi_regdate', models.CharField(max_length=50)),
                ('nsi_title', models.CharField(max_length=50, null=True)),
                ('nsi_form_info', models.TextField()),
                ('nsi_account', models.CharField(max_length=255)),
                ('nsi_bankcode', models.CharField(max_length=10)),
            ],
        ),
    ]
